<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Source\WaterMargin.Localization\WaterMargin.Localization.csproj" />
    <ProjectReference Include="..\..\Tools\WaterMargin.Localization.Compiler\WaterMargin.Localization.Compiler.csproj" />
  </ItemGroup>

</Project>
